core/urls.py
from django.urls import path

from .views import (collage_api, courses_api, courses_semster, major_api,
                    register, staff_api, students_api, test_view)

app_name = 'coreapp'

urlpatterns = [
    path('', test_view, name='home'),
    path('register', register, name='register'),
    path('api/collage/', collage_api, name='collage_api'),
    path('api/major/', major_api, name='major_api'),
    path('api/courses/', courses_api, name='courses_api'),
    path('api/student/', students_api, name='students_api'),
    path('api/staff/', staff_api, name='staff_api'),
    path('api/scourses/', courses_semster, name='courses_semster'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls', namespace='coreapp')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('uapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
<footer
  class="p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 mt-16"
>
  <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"
    >© 2022 <a href="https://flowbite.com/" class="hover:underline">CRM™</a>.
    All Rights Reserved.
  </span>
  <ul
    class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0"
  >
    <li>
      <a href="#" class="mr-4 hover:underline md:mr-6">Help</a>
    </li>
    <li>
      <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
    </li>
    <li>
      <a href="#" class="mr-4 hover:underline md:mr-6">University</a>
    </li>
    <li>
      <a href="#" class="hover:underline">Contact</a>
    </li>
  </ul>
</footer>

templates/components/navbar.html
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="{% url 'coreapp:home' %}" class="flex items-center">
      <span
        class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"
      >
        CRM</span
      >
    </a>
    <div class="flex items-center md:order-2" id="user_drop_open">
      <button
        type="button"
        class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
        id="user-menu-button"
        aria-expanded="false"
        data-dropdown-toggle="user-dropdown"
        data-dropdown-placement="bottom"
      >
        <span class="sr-only">Open user menu</span>
        <img
          class="w-8 h-8 rounded-full object-cover"
          src="{{std.std_image.url}}"
          alt="user photo"
        />
      </button>
      <!-- Dropdown menu -->
      <div
        class="z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 hidden"
        id="user-dropdown"
        style="
          position: absolute;
          inset: 0px 0px auto auto;
          margin: 0px;
          transform: translate(-10px, 55px);
        "
        data-popper-reference-hidden=""
        data-popper-escaped=""
        data-popper-placement="bottom"
      >
        <div class="py-3 px-4">
          <span class="block text-sm text-gray-900 dark:text-white"
            >{{request.user.first_name}} {{request.user.last_name}}</span
          >
          <span
            class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"
            >{{request.user.username}}</span
          >
        </div>
        <ul class="py-1" aria-labelledby="user-menu-button">
          <li>
            <a
              href="{% url 'coreapp:register' %}"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Registers</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Courses</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Settings</a
            >
          </li>
          <li>
            <a
              href="#"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Financial Info</a
            >
          </li>
          <li>
            <a
              href="/accounts/logout/"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Sign out</a
            >
          </li>
        </ul>
      </div>
      <button
        data-collapse-toggle="mobile-menu-2"
        type="button"
        class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="mobile-menu-2"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg
          class="w-6 h-6"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>
  </div>
</nav>